import Foundation

/**
 Samples
 
 The set of text samples shown to users formatted as Swift arrays. Each array contains elements of type `(String, String)` where the first string represents the sample template shown for a singular pronoun and the second string represents the template shown for a plural pronoun (like "they"). Each sample is annotated with placeholder codes which are preceded by semicolons; these codes are replaced with the proper matching pronoun or name from the user's enterred data.
 */

struct Samples {
    /**
     sources for the casual corpus include text written by me and random sentences containing pronouns pulled from yourdictionary.com and curated by me
     */
    static let casual = [ //Samples for the "casual" context
        ("Hey there, how are you, ;name?","Hey there, how are you, ;name?"),
        ("What do you think about ;name?","What do you think about ;name?"),
        ("Today I met ;name, ;he seems nice!","Today I met ;name, ;he seem nice!"),
        ("Did you hear what happened to ;name yesterday?","Did you hear what happened to ;name yesterday?"),
        ("Was this just a personal thing between you and ;name?","Was this just a personal thing between you and ;name?"),
        ("It's so good to see you, ;name","It's so good to see you, ;name"),
        ("I hear that ;name is pretty good at tennis","I hear that ;name is pretty good at tennis"),
        ("If ;he has time to do that, ;he has time to talk to the commissioner.","If ;he have time to do that, ;he have time to talk to the commissioner."),
        ("Music, ;he says, helps plants grow","Music, ;he say, helps plants grow healthier"),
        ("Somebody says ;he's a bit loony","Somebody says ;he're a bit loony"),
        ("I hear ;he really wants to go to school","I hear ;he really want to go to school"),
        (";he was born like this!",";he were born like this!"),
        (";he could live a long time",";he could live a long time"),
        ("I'm glad ;he recovered, last time I heard ;he was in the hospital!","I'm glad ;he recovered, last time I heard ;he were in the hospital!"),
        (";his mother remarried and ;he got a new last name",";his mother remarried and ;he got a new last name"),
        (";he had final say.",";he had final say."),
        (";he lifted a brow.",";he lifted a brow."),
        ("I couldn't have possibly guessed that ;name knew so much about Phonecian history!","I couldn't have possibly guessed that ;name knew so much about Phonecian history!"),
        (";he didn't need proof.",";he didn't need proof."),
        (";he grinned and waved.",";he grinned and waved."),
        (";he wanted my opinion.",";he wanted my opinion."),
        (";he wouldn't like that.",";he wouldn't like that."),
        ("I hope ;name likes us all.","I hope ;name likes us all."),
        (";name's right but I don't wanna admit it",";name's right but I don't wanna admit it"),
        (";he hates when businesses upcharge for ice",";he hate when businesses upcharge for ice"),
        (";name convinced like half the class ;he arm wrestled the king of Jordan",";name convinced like half the class ;he arm wrestled the king of Jordan"),
        ("I can't believe that ;he doesn't like ice cream","I can't believe that ;he don't like ice cream"),
        (";name's fun to play videogames with",";name's fun to play videogames with"),
        (";he shook ;his head and rolled ;his eyes.",";he shook ;his head and rolled ;his eyes."),
        ("No wonder ;he was upset in the stair room.","No wonder ;he were upset in the stair room."),
        ("What are you doing, ;name?","What are you doing, ;name?"),
        ("I don't think that's how that works, ;name","I don't think that's how that works, ;name"),
        ("Well I think that's very exciting, ;name!","Well I think that's very exciting, ;name!"),
        ("There's no way that's true, ;name","There's no way that's true, ;name"),
        (" Where did ;he go?  ;name was just here."," Where did ;he go?  ;name was just here."),
        (";name said everyone was doing it.  So I did it.",";name said everyone was doing it.  So I did it."),
        (";name seems like ;he thrives on danger",";name seems like ;he thrive on danger"),
        ("Does ;he always have that grin?","Do ;he always have that grin?"),
        (";name asked me to meet ;him here",";name asked me to meet ;him here"),
        (";he always looks so nice!",";he alway look so nice!"),
        ("Ask ;him if ;he will help","Ask ;him if ;he will help"),
        ("What's ;he looking for?","What're ;he looking for?"),
        ("No, ;he is here","No, ;he are here"),
        ("Yeah, ;he finished a while ago","Yeah, ;he finished a while ago"),
        ("I want to hear everything ;he said","I want to hear everything ;he said"),
        (" Yeah.  And ;he still went to the party."," Yeah.  And ;he still went to the party."),
        ("Does ;he seem a little moody?","Do ;he seem a little movie?"),
        ("I think ;he knew all along","I think ;he knew all along"),
        ("I don't know much about ;him, I suppose.","I don't know much about ;him, I suppose."),
        ("I'm going to get some strawberry milk, do you want some, ;name?","I'm going to get some strawberry milk, do you want some, ;name?"),
        ("What more can I do, ;name?","What more can I do, ;name?"),
        ("This is a very serious decision, have you thought this through, ;name?","This is a very serious decision, have you thought this through, ;name?"),
        ("Does ;he get airsick?","Do ;he get airsick?"),
        ("Why would ;he do that?","Why would ;he do that?"),
        (";he smiled up at Alex.",";he smiled up at Alex."),
        (";name's new computer has a faster processor but less memory; ;he's not sure if it's really better.",";name's new computer has a faster processor but less memory; ;he're not sure if it's really better."),
        (";he glanced at Carmen.",";he glanced at Carmen."),
        ("Hey, it's ;name's birthday, do something nice for ;him! ","Hey, it's ;name's birthday, do something nice for ;him! "),
        ("What did ;he eat today?","What did ;he eat today?"),
        (";name and I met at the convention last year",";name and I met at the convention last year"),
        (";he made a face at him.",";he made a face at him."),
        (";he hesitated a moment.",";he hesitated a moment."),
        (";name lost ;his phone, have you seen it?",";name lost ;his phone, have you seen it?"),
        (";he spoke in a cool tone.",";he spoke in a cool tone."),
        (";he eyed his lean frame.",";he eyed his lean frame."),
        ("How could I blame ;him?","How could I blame ;him?"),
        (";he squeezed Alex's hand.",";he squeezed Alex's hand."),
        (";he'd deal with him later.",";he'd deal with him later."),
        (";he laughed without humor.",";he laughed without humor."),
        ("Immediately ;he was alert.","Immediately ;he was alert."),
        (";he shook ;his head soberly.",";he shook ;his head soberly."),
        (";name speaks three languages, but only knows a little Lithuanian.",";name speaks three languages, but only knows a little Lithuanian."),
        (";he met his gaze defiantly.",";he met his gaze defiantly."),
        (";name just completely destroyed me at shuffleboard!",";name just completely destroyed me at shuffleboard!"),
        ("I glanced up at ;his face.","I glanced up at ;his face."),
        ("Did ;he have a window seat?","Did ;he have a window seat?"),
        (";he'll be closer to her age.",";he'll be closer to her age."),
        (";he kept begging to go away.",";he kept begging to go away."),
        ("I doubt if ;he'll go to you.","I doubt if ;he'll go to you."),
        (";he was invited to the party.",";he was invited to the party."),
        ("I'm not sure I like ;name's new pajamas with the penguins on them.","I'm not sure I like ;name's new pajamas with the penguins on them."),
        (";name and I disagree on that new movie, but I see ;his point",";name and I disagree on that new movie, but I see ;his point"),
        (";he finally looked up at him.",";he finally looked up at him."),
        (";he eyed Dulce distastefully.",";he eyed Dulce distastefully."),
        ("Once again ;he sighed deeply.","Once again ;he sighed deeply."),
        ("Why would ;he want to do that?","Why would ;he want to do that?"),
        ("This isn't the ;name I know!","This isn't the ;name I know!"),
        (";he is so good at sewing!",";he is so good at sewing!"),
        ("No, ;he's playing in ;his room.","No, ;he's playing in ;his room."),
        ("Hopefully ;he wasn't too angry.","Hopefully ;he wasn't too angry."),
        ("I held ;name's hand.","I held ;name's hand."),
        ("he shook ;his head to clear it.","he shook ;his head to clear it."),
        ("Maybe ;he thought it was funny.","Maybe ;he thought it was funny."),
    ]
    /**
     sources for the professional corpus include text written by me and random sentences containing pronouns pulled from yourdictionary.com and curated by me
     */
    static let professional = [ // Samples for the "professional" context
        (";name is on his way, ;he called from ;his cellphone I think. It sounded like the cellphone, at least.",";name is on his way, ;he called from ;his cellphone I think. It sounded like the cellphone, at least."),
        ("I would like to welcome two people who haven't been with us before: ;name and Janice","I would like to welcome two people who haven't been with us before: ;name and Janice"),
        (";name, we're delighted to have you with us today, would you tell us a little bit about what you do?",";name, we're delighted to have you with us today, would you tell us a little bit about what you do?"),
        (";name has carefully read and heard about all of the things that the group has discussed up until now.",";name has carefully read and heard about all of the things that the group has discussed up until now."),
        (";name, if you wouldn't mind giving some opening remarks",";name, if you wouldn't mind giving some opening remarks"),
        ("And many thanks to Eunice and ;name for lots of hard work and for really making a big leap forward.","And many thanks to Eunice and ;name for lots of hard work and for really making a big leap forward."),
        ("I noted to ;name that the passage of this document from our office to you in some cases was not as smooth as it might have been.","I noted to ;name that the passage of this document from our office to you in some cases was not as smooth as it might have been."),
        (";name actually showed me a wonderful trick to that, if you press shift as well as command, it won't match formatting",";name actually showed me a wonderful trick to that, if you press shift as well as command, it won't match formatting"),
        ("I don't know if ;he was at the last meeting, I don't see anything in ;his notes","I don't know if ;he was at the last meeting, I don't see anything in ;his notes"),
        ("I don't know if ;name noticed their absence or not, but we did. And we want to correct that.","I don't know if ;name noticed their absence or not, but we did. And we want to correct that."),
        ("And then, I would just like in closing to say that ;name is right in saying we have got a good deal of work ahead of us, even though we got a lot accomplished.","And then, I would just like in closing to say that ;name is right in saying we have got a good deal of work ahead of us, even though we got a lot accomplished."),
        ("Our objective is, I would say in the next 10 days or so to find a way to get a draft out to the public. ;name, can you get on that?","Our objective is, I would say in the next 10 days or so to find a way to get a draft out to the public. ;name, can you get on that?"),
        ("I don't want to force ;name to get another draft to you to review in such a short time.","I don't want to force ;name to get another draft to you to review in such a short time."),
        ("I'd like to turn it over to ;name to talk about the Atlanta hearings","I'd like to turn it over to ;name to talk about the Atlanta hearings"),
        ("And that if we do all that well with the help and participation from ;name, we will get a lot of good advice that we can use and take advantage of.","And that if we do all that well with the help and participation from ;name, we will get a lot of good advice that we can use and take advantage of."),
        (";name is right that may get some advice that we are not happy about, but I think that is just part of the process.",";name is right that may get some advice that we are not happy about, but I think that is just part of the process."),
        ("And we are confident that ;name can handle that.","And we are confident that ;name can handle that."),
        (";name, could you put those changes up on our website?",";name, could you put those changes up on our website?"),
        (";name knows that each of you have your own networks and a collection of colleagues, teachers, and scholars in the field",";name knows that each of you have your own networks and a collection of colleagues, teachers, and scholars in the field"),
        ("In the case that if ;name wants to distribute it themself, that's fine, too.","In the case that if ;name wants to distribute it themself, that's fine, too."),
        ("Now, ;name, will you please be able to tell us by e-mail when the drafts can be distributed? I assume it's too early at this point?","Now, ;name, will you please be able to tell us by e-mail when the drafts can be distributed? I assume it's too early at this point?"),
        ("And then, based on ;name's review, there will be a second draft. And then, I will help ;him estimate the final call on it.","And then, based on ;name's review, there will be a second draft. And then, I will help ;him estimate the final call on it."),
        ("But as soon as that is available, we will make it available to ;name in both hard and electronic versions to do as ;he sees fit.","But as soon as that is available, we will make it available to ;name in both hard and electronic versions to do as ;he see fit."),
        ("According to ;name, that was way way prior.","According to ;name, that was way way prior."),
        (";name, would you like to kind of update us on anything, any thoughts that might be on your mind?",";name, would you like to kind of update us on anything, any thoughts that might be on your mind?"),
        ("I wasn't expecting that, but ;he should be able to handle it.","I wasn't expecting that, but ;he should be able to handle it."),
        ("Are you going to talk about the Technical Committee phone call, ;name, in terms of an update? Or do you want me to start it?","Are you going to talk about the Technical Committee phone call, ;name, in terms of an update? Or do you want me to start it?"),
        ("And ;he was pleased to hear that we are now up to six.","And ;he were pleased to hear that we are now up to six."),
        ("And also we had a conversation with ;him about untimed tests where ;he was, I think, of two different minds.","And also we had a conversation with ;him about untimed tests where ;he were, I think, of two different minds."),
        ("When this conversation was discussed in the Mathematics Committee, ;name, amongst others but not alone, worried a lot about the sort of logistics and administrative complications that could ensue from an untimed test, to say nothing about the comparability issues.","When this conversation was discussed in the Mathematics Committee, ;name, amongst others but not alone, worried a lot about the sort of logistics and administrative complications that could ensue from an untimed test, to say nothing about the comparability issues."),
        ("I don't know. ;name, do you want to weigh in on that?","I don't know. ;name, do you want to weigh in on that?"),
        ("I don't know if ;name can help me recall the time, but I know it was for the writing assessment.","I don't know if ;name can help me recall the time, but I know it was for the writing assessment."),
        ("And ;he found that with the additional time, it made almost no difference.","And ;he found that with the additional time, it made almost no difference."),
        ("So I just think we need to take what ;name said into account, too, when we are discussing time.","So I just think we need to take what ;name said into account, too, when we are discussing time."),
        ("I don't think other sites may really take advantage of the opportunity, like ;name says.","I don't think other sites may really take advantage of the opportunity, like ;name says."),
        ("So it just really increases the standardization. And that was another concern of ;name's.","So it just really increases the standardization. And that was another concern of ;name's."),
        ("And there, the issue of comparability came up in sort of when ;he first alluded to it.","And there, the issue of comparability came up in sort of when ;he first alluded to it."),
        ("In fact, if ;name didn't have this second extended constructed item, ;he wouldn't have anything, but ;he would have something else that would take time.","In fact, if ;name didn't have this second extended constructed item, ;he wouldn't have anything, but ;he would have something else that would take time."),
        ("Just one thing going back to the issue of time before you speak, ;name","Just one thing going back to the issue of time before you speak, ;name"),
        ("I really would like for this committee to make that decision about whether or not we want to have an untimed test or not, like ;name said.","I really would like for this committee to make that decision about whether or not we want to have an untimed test or not, like ;name said."),
        ("I think it can be something that would be researched indeed, but ;name and I would like for us to make that decision and indeed any kind of accommodations.","I think it can be something that would be researched indeed, but ;name and I would like for us to make that decision and indeed any kind of accommodations."),
        ("I think we need to be very specific about what we want. And they need to be standardized for the very reasons that ;name was addressing.","I think we need to be very specific about what we want. And they need to be standardized for the very reasons that ;name was addressing."),
        ("Steven had his hand up first. And then, ;name, we'll come back to you.","Steven had his hand up first. And then, ;name, we'll come back to you."),
        ("That's a good point, ;name. Let's discuss that right now.","That's a good point, ;name. Let's discuss that right now."),
        ("Well, I would just build on what ;name said, and my suggestion was to sort of think of some sort of compromise in all of this.","Well, I would just build on what ;name said, and my suggestion was to sort of think of some sort of compromise in all of this."),
        ("But, you know, it could be that based on ;name's information, we may expand the time, but not appreciably.","But, you know, it could be that based on ;name's information, we may expand the time, but not appreciably."),
        ("But an intact form, I don't see how you could do it, ;name.","But an intact form, I don't see how you could do it, ;name."),
        ("And so ;name is right. We have to do a whole sample 45 minutes and then a whole sample 60 minutes and see which way it works better, and then, use the data from whichever sample.","And so ;name is right. We have to do a whole sample 45 minutes and then a whole sample 60 minutes and see which way it works better, and then, use the data from whichever sample."),
        (";name, do you want to respond to that?",";name, do you want to respond to that?"),
        (";name is right; we need to make a choice now. Go with it now with the understanding that ;he and I can do a research study around it.",";name is right; we need to make a choice now. Go with it now with the understanding that ;he and I can do a research study around it."),
        ("Because there are so many things that Pepper is involved in, Pepper and ;name, I just want to make sure that they get on the table.","Because there are so many things that Pepper is involved in, Pepper and ;name, I just want to make sure that they get on the table."),
        (";name said the work chat is down. Is it down for anyone else?",";name said the work chat is down. Is it down for anyone else?"),
        ("I thought we might begin by having ;name and perhaps Thomas telling us what items that were in the minutes that were included in the draft.","I thought we might begin by having ;name and perhaps Thomas telling us what items that were in the minutes that were included in the draft."),
        ("And there is a point which ;name said that isn't exactly captured in the document, but could be or should be, if we still agree on that point.","And there is a point which ;name said that isn't exactly captured in the document, but could be or should be, if we still agree on that point."),
        ("You might want to double check that, ;name","You might want to double check that, ;name"),
        ("If ;name could go back to the last slide so we could see ;his proposal text, I'd like that","If ;name could go back to the last slide so we could see ;his proposal text, I'd like that"),
        ("So your take on it, ;name, is that this test will not provide descriptive or diagnostic information.","So your take on it, ;name, is that this test will not provide descriptive or diagnostic information."),
        ("And I think the kind of statement that ;name picked up on 37 is not consistent with that.","And I think the kind of statement that ;name picked up on 37 is not consistent with that."),
        (";name and I don't think the document is going to be designed to do that.",";name and I don't think the document is going to be designed to do that."),
        ("I would argue that we have because the framework is rather rigorous in the sense of what it is accomplishing, don't you think, ;name?","I would argue that we have because the framework is rather rigorous in the sense of what it is accomplishing, don't you think, ;name?"),
        ("would disagree with what you said, ;name. I think though the way it's stated here, it could be interpreted that I now have useful instructional information with respect to a particular student.","would disagree with what you said, ;name. I think though the way it's stated here, it could be interpreted that I now have useful instructional information with respect to a particular student."),
        ("What ;he communicated there I don't think is clear; could we get more of ;his original message in there?","What ;he communicated there I don't think is clear; could we get more of ;his original message in there?"),
        ("I can see that ;name wants to jump in there","I can see that ;name wants to jump in there"),
        ("While I appreciate ;name's contribution, I think we need to totally change directions here","While I appreciate ;name's contribution, I think we need to totally change directions here"),
        (";name, how would you augment that sentence?",";name, how would you augment that sentence?"),
    ]
    /**
     sources for the academic corpus include text written by me and random sentences containing pronouns pulled from yourdictionary.com and curated by me
     */
    static let academic = [ // Samples for the "academic" context
        (";name claims that Henry James bit off more than he could chew in this novel and many readers agree",";name claims that Henry James bit off more than he could chew in this novel and many readers agree"),
        ("There's an important theme of fluidity in this novel, ;name, don't you think?","There's an important theme of fluidity in this novel, ;name, don't you think?"),
        (";he goes to the lectures and classes on how the variable is measured",";he goes to the lectures and classes on how the variable is measured"),
        ("I'd recommend Alain Finkeilkraut's dissertation on identity to you, ;name","I'd recommend Alain Finkeilkraut's dissertation on identity to you, ;name"),
        ("Oh my gosh, ;name, you have to read the part where he twists Moronao's arm!","Oh my gosh, ;name, you have to read the part where he twists Moronao's arm!"),
        ("In the course with Professor Katopodes, ;he and I always get into semantic arguments","In the course with Professor Katopodes, ;he and I always get into semantic arguments"),
        ("Hey, ;name, do you know when the paper is due?","Hey, ;name, do you know when the paper is due?"),
        ("I liked ;name's paper on the author's correspondence","I liked ;name's paper on the author's correspondence"),
        (";he noticed how the character's name is only revealed on page 72.",";he noticed how the character's name is only revealed on page 72."),
        ("The teacher's lecture on the evolution of ducks was interesting to ;him","The teacher's lecture on the evolution of ducks was interesting to ;him"),
        ("I thought ;name's advice was super useful on the heat transfer problems","I thought ;name's advice was super useful on the heat transfer problems"),
        (";name, what class are you signing up for?",";name, what class are you signing up for?"),
        ("I don't find the history of Ypsilanti that interesting either, ;name.","I don't find the history of Ypsilanti that interesting either, ;name."),
        ("I mostly agree with ;name, I think ;his paper ignores the is/ought fallacy, though.","I mostly agree with ;name, I think ;his paper ignores the is/ought fallacy, though."),
        ("The did you do the reading on the HMS Beagle, ;name?","The did you do the reading on the HMS Beagle, ;name?"),
        ("If you lived back then, ;name, what would you have done?","If you lived back then, ;name, what would you have done?"),
        ("In regards to axioms, ;his argument breaks down a little","In regards to axioms, ;his argument breaks down a little"),
        ("I didn't know you knew Latin, ;name?","I didn't know you knew Latin, ;name?"),
        ("That's a good point, ;name, I didn't remember that $10 was worth more back then","That's a good point, ;name, I didn't remember that $10 was worth more back then"),
        ("I think I know more about the stress strain curve than ;name","I think I know more about the stress strain curve than ;name"),
        (";name's fitting of the Phillips curve here is really smart! But what was ;he doing in step 3?",";name's fitting of the Phillips curve here is really smart! But what were ;he doing in step 3?"),
        ("Your paper was very good, ;name, but an analysis of the original untranslated text would have improved it","Your paper was very good, ;name, but an analysis of the original untranslated text would have improved it"),
        (";his participation in the discussion was very welcome",";his participation in the discussion was very welcome"),
        (";name and Floyd were probably the best students",";name and Floyd were probably the best students"),
        ("You should really read this book on swans, ;name","You should really read this book on swans, ;name"),
        (";name's quenelle technique is really unique, but ;he knows what ;he's doing.",";name's quenelle technique is really unique, but ;he know what ;he're doing."),
        ("I don't think ;name's argument is complete without acknowledging W.E.B. DuBois, though.","I don't think ;name's argument is complete without acknowledging W.E.B. DuBois, though."),
        ("You can get a good job with that degree, ;name! Do you want to be an engineer?","You can get a good job with that degree, ;name! Do you want to be an engineer?"),
        ("Courbet was ahead of the time, ;name, but I don't think you can see that","Courbet was ahead of the time, ;name, but I don't think you can see that"),
        ("Does ;he know what key that Bartok peice was in?","Do ;he know what key that Bartok peice is in?"),
        ("I really didn't understand ;name's explanation on the difference between lumens and candelas","I really didn't understand ;name's explanation on the difference between lumens and candelas"),
        ("This paper was interesting, but I thought ;name's tangent on all the former mayors of New York was not as focused as it could be","This paper was interesting, but I thought ;name's tangent on all the former mayors of New York was not as focused as it could be"),
        ("How do you think chords work in John Mayer's work, ;name?","How do you think chords work in John Mayer's work, ;name?"),
        (";name figured out a way to enumerate our data.",";name figured out a way to enumerate our data."),
        ("Correlation doesn't imply causation, ;name!","Correlation doesn't imply causation, ;name!"),
        ("Mitochondria are the the powerhouse of cells, even ;his","Mitochondria are the the powerhouse of cells, even ;his"),
        ("Your code's been compiling forever, ;name!","Your code's been compiling forever, ;name!"),
        ("I can't believe ;name actually likes Xenocide. I guess I just don't like ;his taste in Orson Scott Card books.","I can't believe ;name actually likes Xenocide. I guess I just don't like ;his taste in Orson Scott Card books."),
        ("This problem is essentially correct, ;name, but you mixed up Kirchoff's first and second laws","This problem is essentially correct, ;name, but you mixed up Kirchoff's first and second laws"),
        (";name did a good job figuring out that ;he can solve the problem faster with completing-the-square than with the quadratic formula.",";name did a good job figuring out that ;he can solve the problem faster with completing-the-square than with the quadratic formula."),
        ("Oh, ;name is right! We wrote momentum as acceleration times mass, but ;he wrote that it was velocity times mass. ","Oh, ;name is right! We wrote momentum as acceleration times mass, but ;he wrote that it was velocity times mass. "),
    ]
    static func getSingular(samples: [(String, String)]) -> [String] { // Extracts the singular samples from a set of samples
        return samples.map({$0.0})
    }
    static func getPlural(samples: [(String, String)]) -> [String] { // Extracts the plural samples from a set of samples
        return samples.map({$0.1})
    }
}
